export const env = {
  GOOGLE_MAPS_API_KEY: import.meta.env.VITE_APP_GOOGLE_MAPS_API_KEY,
  GOOGLE_MAPS_MAP_ID: import.meta.env.VITE_APP_GOOGLE_MAPS_MAP_ID,
  SECRET_KEY: import.meta.env.VITE_APP_SECRET_KEY,
  API_BASE_URL: import.meta.env.VITE_APP_API_BASE_URL,
  GOOGLE_AUTH_API_KEY: import.meta.env.VITE_APP_GOOGLE_AUTH_API_KEY,
  REDIRECT_URL: import.meta.env.VITE_APP_REDIRECT_URL,
  BACKBLAZE_BUCKET_NAME: import.meta.env.VITE_APP_BACKBLAZE_BUCKET_NAME,
};
